default: &default
  adapter: postgresql
  encoding: unicode
  username: nhinguyen
  password: 12345
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: life_api_development

test:
  <<: *default
  database: life_api_test

production:
  <<: *default
  database: life_api_production
  username: life_api
  password: <%= ENV['LIFE_API_DATABASE_PASSWORD'] %>
